eventsim_elt:
  target: dev
  outputs:
    dev:
      account: "{{ env_var('DBT_PROFILE_SNOWFLAKE_ACCOUNT') }}"
      database: analytics_dev
      password: "{{ env_var('DBT_PROFILE_PASSWORD') }}"
      role: DBT_RW
      threads: 1
      schema: "{{ env_var('DBT_PROFILE_SCHEMA') }}"
      type: snowflake
      user: dbt
      warehouse: ETL

    ci:
      account: "{{ env_var('DBT_PROFILE_SNOWFLAKE_ACCOUNT') }}"
      database: analytics_dev
      password: "{{ env_var('DBT_PROFILE_PASSWORD') }}"
      role: DBT_RW
      schema: marts
      threads: 1
      type: snowflake
      user: dbt
      warehouse: ETL      

    preprod:
      account: "{{ env_var('DBT_PROFILE_SNOWFLAKE_ACCOUNT') }}"
      database: analytics_prod
      password: "{{ env_var('DBT_PROFILE_PASSWORD') }}"
      role: DBT_RW
      schema: marts
      threads: 1
      type: snowflake
      user: dbt
      warehouse: ETL      

    prod:
      account: "{{ env_var('DBT_PROFILE_SNOWFLAKE_ACCOUNT') }}"
      database: analytics_prod
      password: "{{ env_var('DBT_PROFILE_PASSWORD') }}"
      role: DBT_RW
      schema: marts
      threads: 1
      type: snowflake
      user: dbt
      warehouse: ETL