/*
  "ts": 1662485273786,
  "sessionId": 30,
  "page": "NextSong",
  "auth": "Logged In",
  "method": "PUT",
  "status": 200,
  "level": "free",
  "itemInSession": 20,
  "city": "Los Angeles",
  "zip": "90045",
  "state": "CA",
  "userAgent": "\"Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36\"",
  "lon": -118.417488,
  "lat": 33.942108,
  "userId": 6,
  "lastName": "King",
  "firstName": "Hollis",
  "gender": "M",
  "registration": 1662460277786,
  "artist": "Kings Of Leon",
  "song": "Use Somebody",
  "duration": 231.81017
*/

CREATE TABLE page_view_events
(
    ts Int64,
    sessionId Int64,
    page String,
    auth String,
    method String,
    status Int64,
    level String,
    itemInSession Int64,
    city String,
    zip String,
    state String,
    userAgent String,
    lon Float64,
    lat Float64,
    userId Int64,
    lastName String,
    firstName String,
    gender String,
    registration Int64,
    artist String,
    song String,
    duration Float64
) ENGINE = MergeTree ORDER BY (ts)