name: integration-snowflake
on:
  pull_request:
    branches: [ main ]
    # paths:
    #   - warehouse/snowflake/data-transformation
  
env:
  DBT_PROFILE_TARGET: prod
  DBT_PROFILE_SNOWFLAKE_ACCOUNT: ${{ secrets.DBT_PROFILE_SNOWFLAKE_ACCOUNT }}
  DBT_PROFILE_USER: ${{ secrets.DBT_PROFILE_USER }}
  DBT_PROFILE_PASSWORD: ${{ secrets.DBT_PROFILE_PASSWORD }}
  DBT_PROFILE_ROLE: DBT_RW
  DBT_PROFILE_DB: PRODUCTION
  DBT_PROFILE_SCHEMA: STAGING
  DBT_PROFILE_WH: ETL
  # DB_HOST: ${{ secrets.DB_HOST }}
  # DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  # GH_REF: ${{ github.ref }}

jobs:
  build-test:
    runs-on: ubuntu-22.04

    steps:
      # Checkout to latest commit of the branch initiating the PR
      - name: Source code - checkout PR
        uses: actions/checkout@v3
      
      # Python setup 
      - name: Python - initial setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      # Install Python deps
      - name: Python - dependencies setup
        run: |
          python -m pip install --upgrade pip
          pip install -r warehouse/snowflake/data-transformation/requirements.txt
          
      # Install dbt packages
      - name: dbt deps
        run: |
          cd warehouse/snowflake/data-transformation/eventsim_elt
          dbt deps

      # SQLFluff
      - name: SQL - Linting
        run: sqlfluff lint warehouse/snowflake/data-transformation/eventsim_elt

      # Checkout main so manifest can be created
      - name: Source code - checkout main
        uses: actions/checkout@v3
        with:
          ref: main
      
      # DBT manifest generation
      - name: SQL - Generate DBT manifest
        run: |
          cd warehouse/snowflake/data-transformation
          dbt deps
          dbt compile --target prod

      # Publish manifest
      - name: SQL - Publish DBT manifest
        uses: actions/upload-artifact@v3
        with:
          name: manifest.json
          path: warehouse/snowflake/data-transformation/target/manifest.json

      # Go back to PR branch
      - name: Source code - checkout PR
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: manifest.json
          path: warehouse/snowflake/data-transformation

      - name: SQL - DBT run
        run: |
          cd warehouse/snowflake/data-transformation
          dbt deps
          dbt run -m state:modified+1 --defer --state . --target ci
          dbt test -m state:modified+1 --defer --state . --target ci


    